### ISSUE TITLE
多尺度特征融合

### ISSUE THREAD

**Issue by yeluohuazhifou** [hzwer/Practical-RIFE#100]
你好，我发现不同的下采样尺度下的flow会呈现不同的现象，单独32倍下采样对快速运动效果更好，单独16倍下采样对细节处理更好，为了结合两者的优点现在的做法是由粗到细的过程，可以对32倍下采样16倍下采样的特征做特征融合，类似FPN的机构，最后原图输出去计算光流吗

**Comment by hzwer** [comment]
因为大部分的数据都是很小分辨率的，所以虽然已经做了一些融合，但是依然能在推理的时候设计各种 trick 来提升效果
我会再试一试结构改进
类似于 IFRNet 或者 SAFA

**Comment by yeluohuazhifou** [comment]
> 因为大部分的数据都是很小分辨率的，所以虽然网络内已经做了一些融合，但是依然能在推理的时候设计各种 trick 来提升效果 我会再试一试结构改进 类似于 IFRNet 或者 SAFA
