### ISSUE TITLE
Accelerated reasoning process

### ISSUE THREAD

**Issue by lgthappy** [hzwer/Practical-RIFE#102]
Hello,I am using the 4.18lite version of the model and have set fp16 and scale=0.5 but it's not as fast as I would like, is there any other way to speed it up?

**Comment by hzwer** [comment]
Hello, there is no solution for now. I am considering rolling out a faster version, but at the cost of reduced effectiveness.

**Comment by TNTwise** [comment]
You can use rife v2, that helps somewhat
