### ISSUE TITLE
Can RIFE fix time parallax (rolling shutter) effect?

### ISSUE THREAD

**Issue by ioctl-user** [hzwer/Practical-RIFE#103]
Which model is the best to fix rolling shutter effect in live video, if any?

If it's not, what could you recommend for this problem?

**Comment by flowreen** [comment]
ChatGPT said no.
"Since rolling shutter is a spatial distortion caused by the sensor, RIFE may not be able to directly fix these artifacts because it deals with temporal interpolation between frames, not spatial correction within individual frames."
https://chatgpt.com/share/66e5e70e-9260-800b-a1ba-86483eec1810

**Comment by ioctl-user** [comment]
It would appear, that RIFE is very close to solve this problem, because rolling shutter fix is the same as frame interpolation with time shifts of parts of the frame relative to each other.

I.e, simple frame interpolation works like this (vertical is frame content, horizontal is time of frame capture):
```
|       |       |       |       |       |                |   |   |   |   |   |   |   |   |   |   |
|       |       |       |       |       |                |   |   |   |   |   |   |   |   |   |   |
|       |       |       |       |       |                |   |   |   |   |   |   |   |   |   |   |
|       |       |       |       |       |         to     |   |   |   |   |   |   |   |   |   |   |
|       |       |       |       |       |                |   |   |   |   |   |   |   |   |   |   |
|       |       |       |       |       |                |   |   |   |   |   |   |   |   |   |   |
|       |       |       |       |       |                |   |   |   |   |   |   |   |   |   |   |
|       |       |       |       |       |                |   |   |   |   |   |   |   |   |   |   |
```

While rolling shutter fix with frame interpolation should works like this:
```
|       |       |       |       |       |                |   |   |   |   |   |   |   |   |   |   |
 |       |       |       |       |       |               |   |   |   |   |   |   |   |   |   |   |
  |       |       |       |       |       |              |   |   |   |   |   |   |   |   |   |   |
   |       |       |       |       |       |      to     |   |   |   |   |   |   |   |   |   |   |
    |       |       |       |       |       |            |   |   |   |   |   |   |   |   |   |   |
     |       |       |       |       |       |           |   |   |   |   |   |   |   |   |   |   |
      |       |       |       |       |       |          |   |   |   |   |   |   |   |   |   |   |
       |       |       |       |       |       |         |   |   |   |   |   |   |   |   |   |   |
```

**Comment by hzwer** [comment]
You may check these works. https://scholar.google.com/scholar?hl=zh-CN&as_sdt=2005&sciodt=0%2C5&cites=12783272439091205239&scipsc=1&q=rolling+shutter&btnG=

**Comment by ioctl-user** [comment]
> You may check these works. https://scholar.google.com/scholar?hl=zh-CN&as_sdt=2005&sciodt=0%2C5&cites=12783272439091205239&scipsc=1&q=rolling+shutter&btnG=
> 
> I notice a paper named [Rolling Shutter Correction with Intermediate Distortion Flow Estimation](https://openaccess.thecvf.com/content/CVPR2024/html/Cao_Rolling_Shutter_Correction_with_Intermediate_Distortion_Flow_Estimation_CVPR_2024_paper.html)

Seems, there is no production-ready projects.

Thank you for answer.
