### ISSUE TITLE
How to use the 4.25 beta

### ISSUE THREAD

**Issue by lgthappy** [hzwer/Practical-RIFE#104]
Hello，how to change the scale_list in 4.25 beta version? I thought I could just replace it directly, but I realized that replacing the train_log directly won't work;

**Comment by hzwer** [comment]
Hello, I just tested it on my laptop and it worked. What issue did you encounter?

**Comment by lgthappy** [comment]
Sorry, I just made a mistake, there is indeed no problem and it works great!

**Comment by lgthappy** [comment]
By the way, again, will this ever come out in a lighter weight.

**Comment by hzwer** [comment]
I'm not sure, we need to wait for today's user feedback.

**Comment by netExtra** [comment]
> I'm not sure, we need to wait for today's user feedback.

Here is today's feedback :)
v4.25 is good and is probably a little better than 4.18 when using SVP as long as I lower the Scene Detection threshold. This slightly increases stuttering but reduces the remaining artefacts. If I lower it to 6% even my Amazing Spider-man horizontal double image issue totally disappears. But the stutters increase and negatively affects everything else.
