### ISSUE TITLE
Rife v4.25 for Live Action

### ISSUE THREAD

**Issue by netExtra** [hzwer/Practical-RIFE#105]
@hzwer 
v4.25 is good and is probably a little better than 4.18 when using SVP as long as I lower the Scene Detection threshold. This slightly increases stuttering but reduces the remaining artefacts. Almost all of my remaining artefacts are reduced. Only my Amazing Spider-man horizontal double image issue remains obvious. But even that can be fixed if I lower SC threshold to 6, but the stutters increase and negatively affects everything else.

When you say that you "increased blocks" does that mean more interpreted frames between real ones?

**Comment by hzwer** [comment]
No, I mean I changed the architecture of Flow model.

**Comment by netExtra** [comment]
> Good News!
> 
> I mean I changed the architecture of Flow model.

I have very little idea how any of this works so apologies in advance for this question. But is it sensible to suggest that you change the architecture of the Flow Model using the model data, or are you already doing that, or is this just total nonsense?

**Comment by hzwer** [comment]
I don't quite understand your question, so I don't know if I have provided the corresponding answer:

v4.25 uses same dataset as v4.18. The number of blocks in the structure of IFNet has been adjusted.

v4.25 still has potential for improvement because it is an intermediate (2/3) training result of the model, and the final model will be available in three days.

**Comment by netExtra** [comment]
> I don't quite understand your question, so I don't know if I have provided the corresponding answer:
> 
> v4.25 uses same dataset as v4.18. The number of blocks in the structure of IFNet has been adjusted.
> 
> v4.25 still has potential for improvement because it is an intermediate (2/3) training result of the model, and the final model will be available in three days.

You have answered my questions and given us hope of even better things to come 🥳
