### ISSUE TITLE
4.25 对 4:3 比例图像生成的结果严重扭曲

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [hzwer/Practical-RIFE#107]
我使用的是 https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan

在 1440x1080 分辨率下，所有画面都存在扭曲
![image](https://github.com/user-attachments/assets/e88e5c93-f0b8-4a0e-9d31-ee34a9ebed16)
在 1280x720 分辨率下画面主体不再有该问题，但在硬字幕边缘仍很明显
![image](https://github.com/user-attachments/assets/0211a4e9-6d84-4cfa-b6b3-b5d78b739616)
在 800x600 下同样的问题再次出现
![image](https://github.com/user-attachments/assets/178f93cf-38c9-43d8-8b00-3f3a0beae3a8)

**Comment by TNTwise** [comment]
Put the issue in the vs rife ncnn repo, I may have messed up the conversion somehow.

**Comment by hzwer** [comment]
似乎不像是原模型的问题。。。

**Comment by TNTwise** [comment]
https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/pull/53/commits/a1d4de733882e9c9eeac5dac395dbeaf37f6de70
Fixed
固定的

**Comment by hzwer** [comment]
"固定的" means stationary 😄 -> "修好了"

**Comment by TNTwise** [comment]
Sorry, I use Google translate😅
