### ISSUE TITLE
Model is not defined

### ISSUE THREAD

**Issue by GlimmerFromDistrict1** [hzwer/Practical-RIFE#11]
File "/Users/x/Practical-RIFE/inference_video.py", line 96, in <module>
    model = Model()
NameError: name 'Model' is not defined

I downloaded the model and added it to a train_log folder. How do I define the model?

**Comment by hzwer** [comment]
https://github.com/hzwer/Practical-RIFE/blob/9172373f4e68750632a51bb86346e32db99491a9/inference_video.py#L93

**Comment by GlimmerFromDistrict1** [comment]
Yes, it's in 

/Users/x/Practical-RIFE/train_log/RIFE_HDv3.py

**Comment by hzwer** [comment]
You can test it at the python command line.
> from train_log.RIFE_HDv3 import Model

**Comment by GlimmerFromDistrict1** [comment]
It turns out that I did not clone the project correctly upon the initial installation. inference_video.py now runs.

**Comment by MonocleRB** [comment]
I'm having this same issue. Doesn't work when cloned by GitHub Desktop or by plain old Git, what did you do differently?

`Please download our model from model list`
`Traceback (most recent call last):`
`  File "/home/MonocleRB/git/Practical-RIFE/inference_video.py", line 96, in <module>`
`    model = Model()`
`            ^^^^^`
`NameError: name 'Model' is not defined`

**Comment by MonocleRB** [comment]
When putting just the offending line (line 96) in its own .py file and running that, I got this:

`\Traceback (most recent call last):`
`  File "/home/landon/git/Practical-RIFE/test.py", line 1, in <module>`
`    from train_log.RIFE_HDv3 import Model`
`  File "/home/landon/git/Practical-RIFE/train_log/RIFE_HDv3.py", line 11, in <module>`
`    from model.loss import *`
`  File "/home/landon/git/Practical-RIFE/model/loss.py", line 5, in <module>`
`    import torchvision.models as models`
`ModuleNotFoundError: No module named 'torchvision'`

So the try/except statement was hiding the real errors.
Installing python-torchvision solved the issue.

**Comment by MonocleRB** [comment]
When putting just the offending line (line 96) in its own .py file and running that, I got this:

`\Traceback (most recent call last):`
`  File "/home/MonocleRB/git/Practical-RIFE/test.py", line 1, in <module>`
`    from train_log.RIFE_HDv3 import Model`
`  File "/home/MonocleRB/git/Practical-RIFE/train_log/RIFE_HDv3.py", line 11, in <module>`
`    from model.loss import *`
`  File "/home/MonocleRB/git/Practical-RIFE/model/loss.py", line 5, in <module>`
`    import torchvision.models as models`
`ModuleNotFoundError: No module named 'torchvision'`

So the try/except statement was hiding the real errors.
Installing python-torchvision solved the issue.
