### ISSUE TITLE
[SUGGESTION] - Official models for more specific tasks

### ISSUE THREAD

**Issue by TNTwise** [hzwer/Practical-RIFE#114]
Thank you for your work and time on this project. I am always excited to see what comes next.
I was wondering if specified models were planned,  for example: one specifically trained for anime interpolation and a separate one trained for realistic interpolation.

**Comment by hzwer** [comment]
Hello, I have tried this before, but I found that I still don't understand how to improve the performance in a certain scenario. I often find that my expectations contradict user feedback. For example, additional training on anime data does not improve the effect in the corresponding scenario.

**Comment by TNTwise** [comment]
Thank you for explaining, again I appreciate the work!

**Comment by flowreen** [comment]
Can u train the model by using a 60 fps source video together with the same video where u remove half of the frames to become a 30 fps video in order for it to learn how to generate the differences? Or model training is harder than that?

**Comment by hzwer** [comment]
In data such as adobe240fps, vimeo90K, the method of data construction is as such. @flowreen
