### ISSUE TITLE
gramloss作用及权重

### ISSUE THREAD

**Issue by Ofrila** [hzwer/Practical-RIFE#119]
你好，这边想请教两个问题：
1.加入gram loss会对动漫插帧效果有提升吗？
2.您这边的gram loss的权重会分配多大呢？会和lap 损失一样的权重大小吗？
期待你的回复，谢谢

**Comment by hzwer** [comment]
你好
1. 据用户反馈是这样的
2. 和 vgg loss 一个权重，面向视觉效果，l1/laplacian 的权重我一般设置成 0.1/0.2
