### ISSUE TITLE
Add anime models

### ISSUE THREAD

**Issue by bropines** [hzwer/Practical-RIFE#12]
Is there any way to add interpolation for animation? The current version of course knows how to make animation smoother, but with a bunch of artifacts. Yes, version 4 has become better compared to the past, but it's still better to make a separate model for animation, as they did for example in real-esrgan

**Comment by hzwer** [comment]
Your suggestion is sound, I can give it a try.

**Comment by bropines** [comment]
Maybe this will help in some way

**Comment by mikebilly** [comment]
yes we want a model that is specially trained for anime to create the best output for anime

**Comment by hzwer** [comment]
In fact, the v4.0 version already contains the data of anime10K. I recently tried developing the "anime" and "real world" versions separately, but found no improvement.

**Comment by bropines** [comment]
Let's just say that even the 4th version with 2d animation is extremely tight. 2.3 is a little better, but still the algorithm stupidly lubricates the animation.

**Comment by hzwer** [comment]
v4.4 model is tuned for anime. We will further optimize it.

**Comment by mikebilly** [comment]
> v4.4 model is tuned for anime. We will further optimize it.

@hzwer Thanks for your devotion to animation, I'd love to see more development regarding animation content!
