### ISSUE TITLE
有没有办法在硬切转场的时候不补帧？

### ISSUE THREAD

**Issue by KiritoGuugk** [hzwer/Practical-RIFE#127]
在硬切转场的时候会补出扭曲的帧，在实际观看时的效果很奇怪。这是补帧的通病吗？除了把视频按转场的时间点切割成一段一段再补帧之外，还有没有别的办法？
使用模型：4.26
![image](https://github.com/user-attachments/assets/f581f244-48dc-4a26-976f-befdac5c136c)
![image](https://github.com/user-attachments/assets/c8bdf320-5890-438e-8888-6c37ca05cd53)

**Comment by routineLife1** [comment]
不是有转场识别么

**Comment by KiritoGuugk** [comment]
> 不是有转场识别么，应该能有个95%精确度

#121 是像这个里面说的修改 `ssim < 0.2` 吗 请问这个应该改大还是改小？改动这个值还会影响到什么？

**Comment by routineLife1** [comment]
调大

**Comment by KiritoGuugk** [comment]
> 调大了漏判会少一些，但是一些运动大的画面也会被判断为转场，流畅度可能会下降，改到自己觉得合适的值为止是最好的

了解了，谢谢。
