### ISSUE TITLE
Where is the 2.3 general model

### ISSUE THREAD

**Issue by dipu-sr** [hzwer/Practical-RIFE#128]
I am looking for Rife 2.3 general model .But I can't find it. i need Rife 2.3 general model

**Comment by hzwer** [comment]
https://drive.google.com/file/d/1VdzN9beh7qi4up9hS7dsEg6WOwUdBh-Q/view?usp=sharing

**Comment by dipu-sr** [comment]
> https://drive.google.com/file/d/1VdzN9beh7qi4up9hS7dsEg6WOwUdBh-Q/view?usp=sharing

tnx bro
