### ISSUE TITLE
Found bugs in inference_img.py

### ISSUE THREAD

**Issue by yaroslav-semeniuk** [hzwer/Practical-RIFE#17]
inference_img.py - line 99

with bugs:
```py
res.append(model.inference(img0, img1, (i+1) * 1. / (n+1), args.scale))
```
fixed:
```py
img_list.append(model.inference(img0, img1, (i+1) / n))
```

1. There's no `res` variable, so I assumed it should be `img_list`
2. Formula was incorrect, resulting in a 0.333 ratio instead of 0.5 for x2 interpolation
3. There's no `args.scale` argument, so I removed it, but you can add it in the list of arguments to keep it

**Comment by hzwer** [comment]
Thank you! Modified it.

**Comment by yaroslav-semeniuk** [comment]
Also, it seems like at line 70, it's not sending the ratio to `model.inference()`, resulting in a 0.5 ratio every time, even if another was provided. But I'm not 100% sure. My fix:
```py
img_list = [img0, model.inference(img0, img1, args.ratio), img1]
```

**Comment by yaroslav-semeniuk** [comment]
Hey @hzwer - I wrote another fix above, but it seems you didn't see it. I don't know GitHub well. Sorry.

**Comment by hzwer** [comment]
@yaroslav-semeniuk Thank you so much for your feedback!

**Comment by oblessnoob** [comment]
> Hey @hzwer - I wrote another fix above, but it seems you didn't see it. I don't know GitHub well. Sorry.

You can try to fork the project to your own branch, fix it, and pull your branch as a pull request.
