### ISSUE TITLE
Dataset for training

### ISSUE THREAD

**Issue by edoli** [hzwer/Practical-RIFE#25]
Hi, I tried to retrain v4.6 model with Vimeo90K dataset. However, the trained model does not perform as well as the provided model for test images. Is 4.6 still using the Vimeo dataset? Or are you using other datasets as well?

**Comment by hzwer** [comment]
Yes, Vimeo90K + ATD12K. But the latter seems to have little effect.

**Comment by edoli** [comment]
The resolution of the ATD12K dataset seems to be FHD (1920x1080). For the ATD12K dataset did you use the same crop size (224x224)? Or larger size?

Additionally, I would like to ask one more question. What was the considerations is choosing the additional data such large images and large motion?

**Comment by hzwer** [comment]
For ATD12K, I will resize images to 480x270 firstly and cropped 224x patches.
Because the users of RIFE mostly care about animation scenes, we hope to add some relevant data to improve the effect.

**Comment by blueblud7** [comment]
@hzwer Hi, I have a quick question. I trained with Vimeo90K & ATD12K, as you described. It had a pretty identical PSNR as the Vimeo test set, but it did not achieve the PSNR with gameplay scenes. Do you have any advice for animation or gameplay datasets to increase PSNR? Or should I run more than 300 epochs for training? Thanks!

**Comment by hzwer** [comment]
@blueblud7 The best way is to use gameplay data for training. As far as I know, the effect of other methods may be relatively poor.
