### ISSUE TITLE
RuntimeError: Argument #8: Padding size should be less than the corresponding input dimension, but got: padding (5, 5) at dimension 2 of input 5

### ISSUE THREAD

**Issue by AIManifest** [hzwer/Practical-RIFE#28]
Hey friends! 

Ran into a really frustrating issue that I can't figure out for the life of me. I've uninstalled and reinstalled dependencies, tried multiple videos and multiple models. I'm running the code on an M2 MAC which was working flawlessly until I closed and reopened VSCode. I'm very frustrated with myself for not being able to figure it out. Please help. Thank you in advance.

File [~/Desktop/AI/Practical-RIFE/interpolator_helper.py:244](https://file+.vscode-resource.vscode-cdn.net/Users/jecarlopalomo/Desktop/AI/Practical-RIFE/~/Desktop/AI/Practical-RIFE/interpolator_helper.py:244), in interpolate_inference_video(args)
    242 I0_small = F.interpolate(I0, (32, 32), mode='bilinear', align_corners=False)
    243 I1_small = F.interpolate(I1, (32, 32), mode='bilinear', align_corners=False)
--> 244 ssim = ssim_matlab(I0_small[:, :3], I1_small[:, :3])
    246 break_flag = False
    247 if ssim > 0.996:

File [~/Desktop/AI/Practical-RIFE/model/pytorch_msssim/__init__.py:107](https://file+.vscode-resource.vscode-cdn.net/Users/jecarlopalomo/Desktop/AI/Practical-RIFE/~/Desktop/AI/Practical-RIFE/model/pytorch_msssim/__init__.py:107), in ssim_matlab(img1, img2, window_size, window, size_average, full, val_range)
    104 img1 = img1.unsqueeze(1)
    105 img2 = img2.unsqueeze(1)
--> 107 mu1 = F.conv3d(F.pad(img1, (5, 5, 5, 5, 5, 5), mode='replicate'), window, padding=padd, groups=1)
    108 mu2 = F.conv3d(F.pad(img2, (5, 5, 5, 5, 5, 5), mode='replicate'), window, padding=padd, groups=1)
    110 mu1_sq = mu1.pow(2)

RuntimeError: Argument #8: Padding size should be less than the corresponding input dimension, but got: padding (5, 5) at dimension 2 of input 5

**Comment by hzwer** [comment]
You can firstly change 
ssim = ssim_matlab(I0_small[:, :3], I1_small[:, :3]) 
=> ssim = 0.995
to work around.
I guess there is something wrong with the pytorch version.

**Comment by AIManifest** [comment]
Yes this worked! Thank you very much friend! Runs stupid fast with 896x512 videos on the Mac M2 with torch.mps inference. Since I have your attention, can you point me to a script or something to run inference with 2.3 model? I have the model weights, just not really sure how to inference because of the dependencies for `inference_video.py`.

**Comment by hzwer** [comment]
You may look up the history: https://github.com/hzwer/Practical-RIFE/blob/327f6ee4766a6bf0da7d115e50e1ce2c1c5a49a0/inference_video.py
