### ISSUE TITLE
能否将V2.3的网络和模型地址也放在这个仓库呢？

### ISSUE THREAD

**Issue by JiadiLee** [hzwer/Practical-RIFE#30]
经过测试对比，发现V2.3模型在某些场景下生成的视觉效果比V4.6还要优秀一些，但是是基于ncnn-vulkan的C++代码进行测试的，想要找python代码发现在这个仓库并没有提供，所以大佬能否将V2.3的网络和模型地址的获取网址也放在这里呢？感谢！

**Comment by hzwer** [comment]
https://github.com/megvii-research/ECCV2022-RIFE/issues/41#issuecomment-785548531
