### ISSUE TITLE
能否导出onnx export？

### ISSUE THREAD

**Issue by juntaosun** [hzwer/Practical-RIFE#33]
能否导出onnx，并使用onnx进行推理呢，代码示例？
Can I export onnx and use onnx for inference? Code example?

**Comment by hzwer** [comment]
可能得问问 onnx 大佬，我并不熟悉这个框架

**Comment by banjaminicc** [comment]
> 能否导出onnx，并使用onnx进行推理呢，代码示例？ Can I export onnx and use onnx for inference? Code example?

You can take a look at vs-mlrt or VSGAN-tensorrt-docker for onnx files.

**Comment by Siziff** [comment]
Here you can find already converted models https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/tag/models
