### ISSUE TITLE
May i know what are the input resolution for both training and testing on 4.x models? 

### ISSUE THREAD

**Issue by Q8sh2ing** [hzwer/Practical-RIFE#37]

**Comment by hzwer** [comment]
The input patch is still 128x128, but is randomly augmented by 2x or 4x before cropping.
What do you mean by testing resolution? The metrics I look at are usually the standard vimeo90k and ATD12k.

**Comment by Q8sh2ing** [comment]
> The input patch is still 128x128, but is randomly augmented by 2x or 4x before cropping.
> The original training data set includes vimeo90k, adobe240fps, ATD12k, the lowest resolution is 256x448, the highest resolution is 720p
> What do you mean by testing resolution? The metrics I look at are usually the standard vimeo90k and ATD12k.

understood, thanks for the info
