### ISSUE TITLE
[Google Colab error] ERROR: No matching distribution found for torchvision==0.7.0

### ISSUE THREAD

**Issue by shinshin86** [hzwer/Practical-RIFE#39]
Hello!
I tried to with Google Colab using `Colab_demo.ipynb` as a reference and encountered the following error.

```
ERROR: Could not find a version that satisfies the requirement torchvision==0.7.0 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0)
ERROR: No matching distribution found for torchvision==0.7.0
```

As a result, I was able to start using it successfully by deleting the line `torchvision==0.7.0` from `requirements.txt`.

For example, I was thinking that if someone like me tries to use Google Colab in the future, I could prepare a `requirements_google_colab.txt` so that they can try it without encountering any problems, what do you think?
(Maybe more `requirements.txt` to manage is not a good thing...)

**Comment by hooke007** [comment]
Yesterday I used latest version of torchvision to test. You could try that.

**Comment by shinshin86** [comment]
@hooke007 Thanks for your comment!
However, I am still getting the same error when I try the latest version.

Error log

```
ERROR: Could not find a version that satisfies the requirement torchvision==0.7.0 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0)
ERROR: No matching distribution found for torchvision==0.7.0
```

Here is the code I ran at Google Colab.

```
%cd /content
!git clone https://github.com/hzwer/Practical-RIFE

%cd /content/Practical-RIFE/
!pip3 install -r requirements.txt
```

What is the latest version of `torchvision`?
(I read and ran `requirements.txt`, but maybe I am misinterpreting your comment)

**Comment by hooke007** [comment]
No, I didn't not run `pip3 install -r requirements.txt`. I pip install every deps one by one instead. Every deps latest version works fine except `numpy`

**Comment by hooke007** [comment]
Or you could edit requirements and then do as previous workflow.
```diff
--- torchvision==0.7.0
+++ torchvision>=0.7.0
```

**Comment by shinshin86** [comment]
> Or you could edit requirements and then do as previous workflow.
> 
> ```diff
> --- torchvision==0.7.0
> +++ torchvision>=0.7.0
> ```

@hooke007  Thank you! It worked with what you taught me!
My question has been answered, so I'll close this issue here.

Thanks for your comment!
