### ISSUE TITLE
Not workin in colab and on local machine

### ISSUE THREAD

**Issue by 2blackbar** [hzwer/Practical-RIFE#4]
Says some crap about siize mismatch, it does not interpolate , in colab it should not have any errors , you just run it and it works, but it doesnt.Maybe it wasnt checked in a while and is broken for a long time.this is local macgine error :
size mismatch for block2.conv0.0.0.weight: copying a param with shape torch.size

blah blah.
Why is this happening ?

**Comment by hzwer** [comment]
This type of problem has been tried to avoid using check branches in the code. Just follow the README to download the weights correctly.
