### ISSUE TITLE
v2.3 missing?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [hzwer/Practical-RIFE#42]
The link to download older models is dead it seems..  Anyone know where to find version 2.3 now?

**Comment by hzwer** [comment]
Fixed.

**Comment by noobtoob4lyfe** [comment]
Thanks for fixing the link, but when I click on the sub-link to attempt to download v2.3 it takes me to this page.  What should I do?
![image](https://github.com/hzwer/Practical-RIFE/assets/43832374/6fd57e34-307d-48f9-b533-8ccf13ee50a8)

**Comment by hzwer** [comment]
There is a google link: https://drive.google.com/file/d/1VdzN9beh7qi4up9hS7dsEg6WOwUdBh-Q/view?usp=sharing
