### ISSUE TITLE
Changelog for model versions

### ISSUE THREAD

**Issue by niqodea** [hzwer/Practical-RIFE#43]
Hello RIFE authors! I often find myself checking out this repository in anticipation of new checkpoint releases. So far, I had a bit of trouble understanding what each version is supposed to improve upon. I could not find any changelog for this, would it be possible to include one somewhere? If one already exists, could you kindly point me to it?

Thank you so much, keep up the great work!

**Comment by hzwer** [comment]
Because I updated the model according to the test loss, I don't know exactly what the improvement will be.

**Comment by hzwer** [comment]
![image](https://github.com/hzwer/Practical-RIFE/assets/10103856/9c79efc3-76c3-4007-a2ab-54ca8ee3f918)

related code: https://drive.google.com/file/d/1IHB35zhO4rr-JSMnpRvHhU9U65Z4giWv/view

**Comment by niqodea** [comment]
Great, thank you a lot!
