### ISSUE TITLE
Model Training

### ISSUE THREAD

**Issue by Siziff** [hzwer/Practical-RIFE#62]
Hi, thank you very much for your project, I saw the script for training the model version 4.12, could you throw in the code for training version 4.15 ??

**Comment by hzwer** [comment]
https://drive.google.com/file/d/19sUMZ-6H7g_hYDjTcqxYu9kE7TqnfS3k/view?usp=sharing

**Comment by Siziff** [comment]
@hzwer Thanks a lot!

**Comment by Siziff** [comment]
@hzwer Hi again :) In this code you have different names of classes and models for training and inference, could you tell me how you run the trained models on inference without correcting the entire training code?

**Comment by hzwer** [comment]
Because the model has changed very little over the years, I only need to incrementally change a few parameters.
