### ISSUE TITLE
Absence of refinenet in training scripts

### ISSUE THREAD

**Issue by niqodea** [hzwer/Practical-RIFE#66]
Hello RIFE authors!

By comparing the original training code [v4.0](https://drive.google.com/file/d/1zoSz7b8c6kUsnd4gYZ_6TrKxa7ghHJWW/view) with the later versions [v4.12](https://drive.google.com/file/d/1IHB35zhO4rr-JSMnpRvHhU9U65Z4giWv/view) and [v4.15](https://drive.google.com/file/d/1IHB35zhO4rr-JSMnpRvHhU9U65Z4giWv/view), it seems like we now no longer train the refinenet, only the flownet. I have some questions about it:

* Is there a specific reason for this?
* Are the refinenet weights ideally independent from the flownet?
* Have you kept the weights of the refinenet fixed from a certain `v4.x` version onwards?
* Isn't keeping the refinenet in the training `forward` pass always important, even when the refinenet is not trained? Without it, we are comparing the ground truth with an unprocessed output that was obtained by simply morphing the two before and after images, instead of the output of the entire model pipeline. Am I missing something?

Also, a request: would it be possible to have a version of the latest training code that enables you to also train the refinenet? I assume it would just be a matter of putting back `contextnet` and `unet`, correct?

Thank you for your time!

**Comment by hzwer** [comment]
Hi, we removed refinenet completely. Because we found that although refinenet improves model evaluation indicators, it often performs poorly in real scenarios.
The output is obtained by merging two warped images.
