### ISSUE TITLE
Deeper guide for arguments

### ISSUE THREAD

**Issue by Nick088Official** [hzwer/Practical-RIFE#67]
Hey sorry to ask this and if i look dumb writing this, but, is there any deeper guide for the arguments you can use?
because the only examples in the repo are:
![image](https://github.com/hzwer/Practical-RIFE/assets/91847579/d1137d79-158e-41e3-ad56-1ce51caba168)
While in inference_video.py there are:
![image](https://github.com/hzwer/Practical-RIFE/assets/91847579/d80d94d7-0127-4f97-b640-248d65b365b9)

And there are some confusion, like the difference between using --UHD and --scale=0.5 as both of them are technically suggested for 4K videos in the code.

**Comment by hzwer** [comment]
Added

**Comment by Nick088Official** [comment]
Hey thank you for adding it
![Screenshot 2024-05-27 140238](https://github.com/hzwer/Practical-RIFE/assets/91847579/c525efc6-9366-4ad8-94d1-30d30cb16ebc)
Sorry if im talking dumb, but could you please explain better what is exp?
I'm not understanding much also the scale parameter as its only definition is that you need to put it to 0.5 for 4k videos.
One last question, if the multi is Interpolation Frame rate multiplier, then why in the examples for X2 interpolation the multi is set to 4, and viceversa?
