### ISSUE TITLE
关于4.18模型权重

### ISSUE THREAD

**Issue by cslvjt** [hzwer/Practical-RIFE#77]
作者您好，感谢您优秀的工作！

我在加载4.18版本的模型权重（从google drive下载）时出现模型权重中包含module.teacher的块，请问是否是模型权重上传错误？
![image](https://github.com/hzwer/Practical-RIFE/assets/65208601/a7058289-b1b6-421e-a01c-9ad7f8f03fd6)

**Comment by cslvjt** [comment]
自己解决了，打扰了。再次感谢作者优秀的工作！

**Comment by shame-e** [comment]
麻烦请问怎么解决的
