### ISSUE TITLE
[BUG] Acceleration, instead of interpolation

### ISSUE THREAD

**Issue by bropines** [hzwer/Practical-RIFE#8]
When testing version 4, a bug was found, because of which the video stupidly accelerates, instead of an upscale. That is, it is improving, but in some moments it stupidly accelerate

**Comment by hzwer** [comment]
I think I found the bug. https://github.com/hzwer/Practical-RIFE/commit/9172373f4e68750632a51bb86346e32db99491a9
Please git pull the new code.

**Comment by bropines** [comment]
It seems like everything is working fine now. True, the speed of work has decreased, but it is critical.  Thanks.
