### ISSUE TITLE
Rife v4.20 is similar to v4.18

### ISSUE THREAD

**Issue by netExtra** [hzwer/Practical-RIFE#80]
Hi @hzwer. 

Thanks for the new Rife model which is much appreciated :) Rife v4.20 may be very slightly worse than v4.18 for artefacts but it is close. Hope this helps a little.

**Comment by hzwer** [comment]
The biggest improvement in this version is the generalization of various timesteps. If you perform 16x interpolation, you should be able to see a big difference.

**Comment by netExtra** [comment]
> The biggest improvement in this version is the generalization of various timesteps. If you perform 16x interpolation, you should be able to see a big difference. Another point is to enhance the accurate perception of timestep, and we see a significant difference in animation scenes.

Not sure we can do that with SVP.

**Comment by elexor** [comment]
Would it be possible to add more scales? With 1080p video, 1/8 isn't low enough for larger motions in all content, including anime.

The stability of the lower scales would need improvement to prevent wobbling from propagating into the final output. I have noticed that models beyond version 4.7 exhibit visible shaking in the final output, especially during slow camera pans. This might be due to the instability of the lower scales.

Thank you, I enjoy seeing your progress.

**Comment by 2994dd42d75b0** [comment]
> The biggest improvement in this version is the generalization of various timesteps. If you perform 16x interpolation, you should be able to see a big difference. Another point is to enhance the accurate perception of timestep, and we see a significant difference in animation scenes.

When using v4.20
model = Model()
NameError: name 'Model' is not defined
Why Help Please v4.18 working

**Comment by hzwer** [comment]
@elexor done

**Comment by elexor** [comment]
Thanks. Unfortunately, the model still can't cope with larger camera movements, It tends to revert to a frame blended appearance. Fast objects in motion don't get shifted to the timestep position between f0 and f1 while visible artifacts are reduced It doesn't look as smooth, It looks more like the original frame rate when it starts blending frames.

After 4.7 the newer models produce a sharper output and static pixels don't get distorted, but it wobbles more during slow movements and frameblends more for large movements

example of how the model frameblends with large motions

Frame blending large motions doesn't appear visually smooth as the object isn't moved to a position in between the two input frames
![{17060F43-9D12-42D2-93B6-E5ACBBDFC2F0}](https://github.com/user-attachments/assets/3b86b1dc-7a0f-4d6d-905c-73b99e12d03d)
(4.25)

same frame but less blended(much more visually smooth in playback)
![{7EF301B1-D443-45CD-B167-B4944B6E13AC}](https://github.com/user-attachments/assets/3e5b9b8e-1835-4bed-8103-864ea2ba73c7)
(4.7 with lower scales)

I also find even / 32 scale to help with really fast motions and large anime character movements, I find different parts of the image have an optimal scale.

Maybe motion magnitude needs to be estimated first and then the appropriate scales can be chosen.

**Comment by 2994dd42d75b0** [comment]
Can you provide me v4.7 link?
Can't find it anywhere
