### ISSUE TITLE
rife 4.20 some motions are not smooth with higher multiples vs older versions

### ISSUE THREAD

**Issue by elexor** [hzwer/Practical-RIFE#81]
A very strange behaviour occurs with this new model in comparison to the previous models, sometimes rife doesn't warp pixels an equal distance apart compromising smooth motion, when it was fine before. It doesn't happen to everything, only certain things.

Attached example where it's obvious, I see it happen in different moments in anime, even when motions are small.

https://github.com/user-attachments/assets/189474ca-03b5-4293-8944-cff67883b953

https://github.com/user-attachments/assets/49791c80-c8a2-4dbd-b251-6066a76dc284

https://github.com/user-attachments/assets/250b426b-c8ca-447f-9a0c-2e73d43d3a9c

**Comment by flowreen** [comment]
Notice how in MPV by pressing '>' button you can see frame by frame that in model 4.19 the eyes object is being moved as a single entity:
https://gyazo.com/547d9551dfe634059d1f5154425e5c37
meanwhile in 4.20 the eyes object is being curved a lot during movement:
https://gyazo.com/f2bff3f2d8f56ef268a3a738907d116e
maybe this is what elexor is reffering to.

**Comment by elexor** [comment]
In this example the 24fps vertical sliding motion is not moving evenly per frame, It actually looks less smooth then 2x  4.20 in this case.

I understand and appreciate what the new model is trying to do, preserve animation hold times with less artifacts.

This effect looks good for 12fps and below animations but I see it's not accurate enough to allways leave the 24fps parts alone. I think this should be in an seperate anime specific model or as a toggleable feature, as people use RIFE for lots of different usecases where accurate specificed timesteps can be important.

**Comment by elexor** [comment]
> Notice how in MPV by pressing '>' button you can see frame by frame that in model 4.19 the eyes object is being moved as a single entity: https://gyazo.com/547d9551dfe634059d1f5154425e5c37 meanwhile in 4.20 the eyes object is being curved (wiggles) a lot during movement: https://gyazo.com/f2bff3f2d8f56ef268a3a738907d116e maybe this is what elexor is reffering to.

You're focused on the wrong thing this is about the camera movement at 3x and you are testing it at 2x, watch my examples

**Comment by flowreen** [comment]
Wow, you're right! In your 4.20 video the right image holds the bottom for 3 frames and tries to stretch the image instead of moving it vertically in the 2 generated RIFE frames.
https://gyazo.com/b5044e4df70337d69adcd7b4cccec573

**Comment by elexor** [comment]
> Wow, you're right! In your 4.20 video the right image holds the bottom for 3 frames and tries to stretch the image instead of moving it vertically in the 2 generated RIFE frames. https://gyazo.com/b5044e4df70337d69adcd7b4cccec573 maybe it's having trouble with the black colored background

Yeah that's it. 
It's a thing in this new model specifically for higher multi anime, it's only ment to happen for animations, to preserve the animation hold times. but often you see it happen by mistake in the 24fps parts like camera movements, not just this scene I see it at least a handful of times in each anime in the wrong place, also happens in live-action video.

**Comment by 2994dd42d75b0** [comment]
When using v4.20 i am getting
model = Model()
NameError: name 'Model' is not defined

How did u run

**Comment by UcodeAvery** [comment]
I spent a couple of hours using wolfram and gpt4 omni to try and convert the rifev4.20py to .onnx, and was unable to.  Could someone link the .onnx ver. of this file they have made? Much appreciated, just dropped $1.7k on making a new build so i can realtime interpolate with rife ai 5x to 120fps

**Comment by UcodeAvery** [comment]
Now that I'm testing it, with TensorRT on and everything, my 4080 super with all proper other components like amd r5 7600, is performing the same as my 2070 with rife.  I'm only able to do 2x 1080@24 --> 1080@48 with the 4080 super rn.  Any suggestions on how to fix this?  It's performing correctly on msi kombuster, but not on svp.

**Comment by flowreen** [comment]
@UcodeAvery i have this short guide for rife in SVP:
https://www.svp-team.com/forum/viewtopic.php?pid=83352#p83352
you should be able to use the frc.frame.resize parameter to downsize the video until you reach your desierd framerate:
https://gyazo.com/51dcb8593e6f31b5912c44940fb5ca9c

**Comment by UcodeAvery** [comment]
@flowreen thanks, i'll look through it.  I should be able to get 1080@24 --> 1080@120 with tensor rt on this build tho, right? https://pcpartpicker.com/list/Nsd8DZ/add_to_cart/

**Comment by UcodeAvery** [comment]
@flowreen your guide is goated and i was able to get the .onnx file using it easily too, tsym, ur a god

**Comment by UcodeAvery** [comment]
@flowreen still having the same issues and it says I don't have access to be able to edit mpv.conf.  Could you help me with rust desk or a service like that? I'll experiment with the updated beta cuda tensor rt versions too

**Comment by flowreen** [comment]
mpv.conf is in write restricted folder, if you drag and drop it in Notepad++, it asks you "do you want to relaunch in admin mode to edit it?" press OK.
Otherwise, copy that file somewhere else, edit it, then copy the new version back.

**Comment by UcodeAvery** [comment]
Editing it with notepad ++ in admin mode worked, thanks.  I have discord, it's "biytes" for my ipad acc and "brited" for my pc acc.  If you could add both I'd appreciate that

**Comment by elexor** [comment]
Inaccurate time-step problem persists in 4.21

**Comment by flowreen** [comment]
Vertical movement now correctly slides the characters in the generated frames on a 3x example:
https://gyazo.com/b0c02215802c760873098aada69c2af6
Looks fixed to me. Thanks! 🥳

**Comment by netExtra** [comment]
Hopefully that is true but it's still performs a little worse than v4.18 for live motion.

**Comment by flowreen** [comment]
Please record and give specific short examples on old vs newer models like elexor did, if u want devs to check the live motion.

**Comment by netExtra** [comment]
I've already done that previously for a major artefact which is still there. Steady improvements have been made since v4.9 until v4.15 then there were a couple of regression models until model v4.18 which improved upon v4.15. v4.19-v4.21 are regression models and hopefully a later model will improve on v4.18.

**Comment by netExtra** [comment]
The issue is that these models are designed from Anime and not for live action, so any benefits we get are just luck. I would like there to be a model focussed on live action but maybe that is too difficult?

**Comment by elexor** [comment]
> Vertical movement now correctly slides the characters in the generated frames on a 3x example: https://gyazo.com/b0c02215802c760873098aada69c2af6 Looks fixed to me. Thanks! 🥳

It's the same as 420. I'd appreciate it, If you don't prematurely call this issue fixed. I will post some more obvious anime examples.

**Comment by hzwer** [comment]
@netExtra I'm checking all the diffs from v418 and v421, and I've actually been adding live action data, but I don't know what's causing the negative feedback.

**Comment by netExtra** [comment]
> @netExtra I'm checking all the diffs from v418 and v421, and I've actually been adding live action data, but I don't know what's causing the negative feedback. One difference is that I seem to have mistakenly removed the "ema" during training.

One example is with Alita Battle Angel starting at 1:34:57 where after jumping off a roof she swings on a power line. The motion before she reaches the power line is smooth on v4.18, a little jerky in v4.20 and very jerky in 4.21. I hope this is a good example for you

**Comment by elexor** [comment]
Here's one example of 4.21 topo 4.7 bottom, the bamboo wall is 24fps and doesn't move an even distance per frame and you can see it stuttering during normal playback. I'm using slowmo to make the issue more visible.

https://github.com/user-attachments/assets/ba3b62df-ed3a-4c30-91e5-b5387b1dd65e

**Comment by elexor** [comment]
4.21 left 4.7 right

https://github.com/user-attachments/assets/fed53454-44d6-4a7f-99d2-804bc11164c6

**Comment by hzwer** [comment]
@elexor @netExtra 
I finetuned v4.21 to get a new version, https://drive.google.com/file/d/1qh2DSA9a1eZUTtZG9U9RQKO7N7OaUJ0_/view?usp=share_link
You may check if this issue was fixed

**Comment by elexor** [comment]
> @elexor @netExtra I finetuned v4.21 to get a new version, https://drive.google.com/file/d/1qh2DSA9a1eZUTtZG9U9RQKO7N7OaUJ0_/view?usp=share_link You may check if this issue was fixed

Thankyou, This looks alot better in my examples then 4.21 and 4.20. It looks similar to 4.18 smoothness

I think netextras issues are different to the reason I opened this issue, so this can be closed.

The model still has room for improvement, compared to 4.7 for medium speed motions (wobbling)
Let me know if you want me to continue testing other things.

https://github.com/user-attachments/assets/15f7f8ae-a02b-4f54-ab0c-cdd9b680385b

**Comment by netExtra** [comment]
> @elexor @netExtra I finetuned v4.21 to get a new version, https://drive.google.com/file/d/1qh2DSA9a1eZUTtZG9U9RQKO7N7OaUJ0_/view?usp=share_link You may check if this issue was fixed

Thanks for the update :) The example I gave you from Alita has improved, but v4.18 is still smoother. I assume that since @elexor has closed this ticket that his issue has been fixed. v4.18 is still the best for live action.

**Comment by elexor** [comment]
> > @elexor @netExtra I finetuned v4.21 to get a new version, https://drive.google.com/file/d/1qh2DSA9a1eZUTtZG9U9RQKO7N7OaUJ0_/view?usp=share_link You may check if this issue was fixed
> 
> Thanks for the update :) The example I gave you from Alita has improved, but v4.18 is still smoother. I assume that since @elexor has closed this ticket that his issue has been fixed. v4.18 is still the best for live action.

My issue was with higher multiples not being smooth, that seems to be addressed by this update. In my examples at least.

**Comment by UcodeAvery** [comment]
im currently using a AMD Ryzen 5 7600 with a 4080super, if i want to rife ai interpolate using 4.18v2 faster with more detail by transcoding rather than plying in real time, which cpu should I get? If I use slow mode, it uses like 75% gpu 100% cpu,  and takes about 40-60 minutes to interpolate 1080@24-->1080@120.  When realtime interpolating, which i assume uses the equivalent to fast mode in the transcoding section, uses 100%gpu and 60%cpu when realtime interpolating from 1080@24-->1080@120.  I bought all the parts to this pc for the purpose of ai frame interpolating anime, so I'd have a budget of probably like $450 for the cpu.

**Comment by hzwer** [comment]
@netExtra I suspect that gram loss is not suitable for live action.
I upload a new model: 
4.23beta for real scenes - 41M - 2024.08.28 | [Google Drive](https://drive.google.com/file/d/1teIROXLAvsvuj6z_l2skrwGXTcOpo5l3/view?usp=sharing)

**Comment by netExtra** [comment]
> @netExtra I suspect that gram loss is not suitable for live action. I upload a new model: 4.23beta for real scenes - 41M - 2024.08.28 | [Google Drive](https://drive.google.com/file/d/1teIROXLAvsvuj6z_l2skrwGXTcOpo5l3/view?usp=sharing)

Just waiting for @WolframRhodium to create the onnx files.

**Comment by WolframRhodium** [comment]
@hzwer The current zip archive for 4.23 uses the lite version of python file instead of the full version.

**Comment by netExtra** [comment]
@hzwer I'm not sure what happened with v4.23 but the video is very choppy and unwatchable.

**Comment by netExtra** [comment]
@hzwer v4.23 was choppy and unwatchable the first couple of times I tried to use it but it is OK now. However in terms of artefacts it is similar to v4.9 and not as good as v4.15/v4.18.
