### ISSUE TITLE
"lite" models for 4.18/4.19/4.20?

### ISSUE THREAD

**Issue by luikaire** [hzwer/Practical-RIFE#87]
Will "lite" models for versions 4.18/4.19/4.20 also be released (4.17-lite seems to be the last one in this category)?

**Comment by hzwer** [comment]
Maybe not, I want to provide a 4.21-lite as an alternative

**Comment by hzwer** [comment]
4.22-lite is released
https://drive.google.com/file/d/1Smy6gY7BkS_RzCjPCbMEy-TsX8Ma5B0R/view?usp=sharing
Not sure if it's good

**Comment by netExtra** [comment]
> 4.22-lite is released https://drive.google.com/file/d/1Smy6gY7BkS_RzCjPCbMEy-TsX8Ma5B0R/view?usp=sharing Not sure if it's good

I don't download "lite" models anymore. Any actual changes to the training etc?

**Comment by hzwer** [comment]
No, some just want faster models at the expense of performance.
