### ISSUE TITLE
v4_18_0703 loss

### ISSUE THREAD

**Issue by yeluohuazhifou** [hzwer/Practical-RIFE#92]
你好，v4_18_0703里面有一个loss_smooth = self.sobel(flow[3], flow[3]*0).mean()，为什么是这样写呢，这样flow的真值是设为0？

**Comment by hzwer** [comment]
因为我偷懒
就是计算了一下图像梯度，和 0 算差值 loss

**Comment by yeluohuazhifou** [comment]
> 因为我偷懒 就是计算了一下图像梯度，和 0 算差值 loss

噢噢，去掉了感觉对效果影响不大

**Comment by hzwer** [comment]
主要为了修以前一些栅栏类重复 pattern 光流乱掉的问题
