### ISSUE TITLE
v4_22_0808训练

### ISSUE THREAD

**Issue by yeluohuazhifou** [hzwer/Practical-RIFE#93]
使用v4.22_0808的代码训练，训练几个epoch之后会出现预测为全黑的图片，暂时未找到原因

**Comment by yeluohuazhifou** [comment]
> 使用v4.22_0808的代码训练，训练几个epoch之后会出现预测为全黑的图片，暂时未找到原因

当出现异常后，后续epoch预测出来的都是全黑的图片

**Comment by hzwer** [comment]
https://github.com/hzwer/Practical-RIFE?tab=readme-ov-file#model-training
用这里的代码
推理代码和训练代码有较大差异，特别是对 teacher 的处理

**Comment by yeluohuazhifou** [comment]
> https://github.com/hzwer/Practical-RIFE?tab=readme-ov-file#model-training 用这里的代码 推理代码和训练代码有较大差异，特别是对 teacher 的处理

dataset.py里的训练文件能提供下吗

**Comment by hzwer** [comment]
你指的是什么 我用的是一个内部的数据平台 数据都是开源下载的

**Comment by yeluohuazhifou** [comment]
> 你指的是什么 我用的是一个内部的数据平台 数据都是开源下载的

噢噢，明白了
