### ISSUE TITLE
Supports 1080p video frame insertion, test to see the runtime is quite slow

### ISSUE THREAD

**Issue by lgthappy** [hzwer/Practical-RIFE#98]
I am using the v4.18 version of the model, does this model support frame interpolation for 1080p resolution video? I tested 360p and 720p resolution video both support frame interpolation, but the runtime is much larger than the 16ms stated in the paper (I tested and found that 360p runtime is 30ms, 720p runtime is 60ms, gpu RXT 3070), so it's weird.

**Comment by hzwer** [comment]
Acceleration can be achieved by selecting 4.22lite or --scale=0.5. 
Some inference frameworks can also provide acceleration, such as https://github.com/nihui/rife-ncnn-vulkan.
Additionally, the paper's testing did not include hard disk read and write times.
